name: mrrescue
summary: Arcade-style fire fighting game
description: |
 Mr. Rescue is an arcade styled 2D action game centered around evacuating
 civilians from burning buildings.

 The game features fast paced fire extinguishing action, intense boss battles,
 a catchy soundtrack and lots of throwing people around in pseudo-randomly
 generated buildings.
adopt-info: mrrescue

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

parts:
  love0.10.2:
    source: https://bitbucket.org/rude/love/downloads/love_0.10.2ppa1_amd64.deb
    plugin: dump
    source:
      - on amd64: https://bitbucket.org/rude/love/downloads/love_0.10.2ppa1_amd64.deb
      - on i386: https://bitbucket.org/rude/love/downloads/love_0.10.2ppa1_i386.deb
      - on armhf: https://bitbucket.org/rude/love/downloads/love_0.10.2ppa1_armhf.deb
    # Suitable stage-packages for LOVE 0.9.x and 0.10.x
    stage-packages:
      - libdevil1c2
      - libfreetype6
      - libgcc1
      - libgl1-mesa-glx
      - libluajit-5.1-2
      - libmodplug1
      - libmpg123-0
      - libopenal1
      - libphysfs1
      - libsdl2-2.0-0
      - libstdc++6
      - libtheora0
      - libvorbisfile3
      - zlib1g

  liblove0.10.2:
    source:
      - on amd64: https://bitbucket.org/rude/love/downloads/liblove0_0.10.2ppa1_amd64.deb
      - on i386: https://bitbucket.org/rude/love/downloads/liblove0_0.10.2ppa1_i386.deb
      - on armhf: https://bitbucket.org/rude/love/downloads/liblove0_0.10.2ppa1_armhf.deb
    plugin: dump
    after:
      - love0.10.2

  mrrescue:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/SimonLarsen/mrrescue/releases/latest -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//')
      LOVE_URL=$(cat releases.json | jq -r ".assets[] | select(.name | test(\"love\")) | .browser_download_url")
      echo "Downloading ${LOVE_URL}..."
      wget --quiet "${LOVE_URL}" -O "${SNAPCRAFT_PART_INSTALL}/game.love"
      rm -f releases.json 2>/dev/null
      snapcraftctl set-version "$VERSION"
    build-packages:
      - jq
      - sed
      - wget
    after:
      - desktop-glib-only
      - liblove0.10.2

apps:
  mrrescue:
    command: bin/desktop-launch $SNAP/usr/bin/love $SNAP/game.love
    plugs:
      - desktop
      - gsettings
      - home
      - joystick
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - wayland
      - x11
